(() => {
  'use strict';
  const KEY = 'xiayibu-v1';
  const names = {overview:'总览',direction:'定方向',companion:'求职伙伴',resume:'简历工坊',tracker:'投递看板',safety:'求职避坑',resources:'公共资源'};
  const stages = ['想投递','已投递','笔试中','面试中','已收到反馈','已结束'];
  const today = () => new Date().toLocaleDateString('sv-SE');
  const uid = () => (globalThis.crypto?.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  const defaults = () => ({profile:{status:'',target:'',city:'',strengths:'',goal:''},tasks:[],jobs:[],resume:{name:'',title:'',phone:'',email:'',city:'',summary:'',experience:'',projects:'',education:'',skills:''},analysisInput:{jd:'',evidence:''}});
  let state = load();
  let filter = '全部';
  let riskText = '';
  let toastTimer;
  let saveTimer;
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const nl = v => esc(v).replace(/\n/g,'<br>');
  const safeUrl = v => { try {const u=new URL(v); return ['https:','http:'].includes(u.protocol) ? u.href : ''} catch {return ''} };
  const trunc = (v,n=140) => String(v||'').slice(0,n);
  function load(){try{const data=JSON.parse(localStorage.getItem(KEY));if(!data||typeof data!=='object'||Array.isArray(data))return defaults();const d=defaults();return {profile:{...d.profile,...data.profile},resume:{...d.resume,...data.resume},analysisInput:{...d.analysisInput,...data.analysisInput},tasks:Array.isArray(data.tasks)?data.tasks.slice(0,300):[],jobs:Array.isArray(data.jobs)?data.jobs.slice(0,500):[]}}catch{return defaults()}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('浏览器存储空间不足，建议先导出备份')}}
  function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
  function count(){return {applied:state.jobs.filter(j=>j.status!=='想投递').length,interviews:state.jobs.filter(j=>j.status==='面试中').length,done:state.tasks.filter(t=>t.done).length}}
  function route(){const hash=location.hash.slice(1);return names[hash]?hash:'overview'}
  function go(name){location.hash=name;window.scrollTo({top:0,behavior:'smooth'});render()}
  function header(kicker,title,sub){return `<div class="page-intro"><div class="eyebrow">${kicker}</div><h1 class="page-title">${title}</h1><p class="subtitle">${sub}</p></div>`}
  function empty(symbol,title,desc,action){return `<div class="empty-state"><div class="empty-symbol">${symbol}</div><h3>${title}</h3><p>${desc}</p>${action||''}</div>`}
  function overview(){const c=count();const pending=state.tasks.filter(t=>!t.done).slice(0,4);const progress=state.tasks.length?Math.round(c.done/state.tasks.length*100):0;const recent=[...state.jobs].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,3);return `<div class="eyebrow">YOUR CAREER, YOUR PACE</div><h1 class="page-title">你好，${state.profile.target?'未来的'+esc(trunc(state.profile.target,18)):'准备出发的人'}。</h1><p class="subtitle" style="margin-bottom:23px">找工作有很多步，我们先走好眼前这一步。</p>
    <section class="hero"><div class="hero-copy"><div class="hero-kicker">✦ NEXT STEP / 求职行动计划</div><h1>下一步，<br><em>从这里开始。</em></h1><p>${state.profile.target?`你正在探索「${esc(trunc(state.profile.target,28))}」方向。把想法写下来，变成一件件能完成的小事。`:'告诉我们你想去哪里。我们会帮你拆出一份可以立刻开始的行动清单。'}</p><div class="hero-actions"><button class="btn btn-primary" data-action="go-direction">${state.profile.target?'调整我的方向':'制定我的计划'} <span>↗</span></button><a class="btn btn-hero-secondary" href="#companion">找伙伴聊聊 ✦</a></div></div><div class="hero-art" aria-hidden="true"><div class="hero-ring"></div><div class="hero-card"><small>PROGRESS / 行动进度</small><strong>${progress}%</strong><div class="bar"><i style="width:${progress}%"></i></div></div><div class="hero-card-bottom">每一步都算数 ↗</div></div></section>
    <div class="section-head"><div><h2>此刻的你</h2><p>这些数字仅来自你在这里保存的记录</p></div></div><div class="cards-3"><div class="stat-card"><div class="stat-top">已投递及后续进展 <span class="stat-icon">↗</span></div><div class="stat-value">${c.applied}<small>个岗位</small></div></div><div class="stat-card"><div class="stat-top">面试进行中 <span class="stat-icon">◎</span></div><div class="stat-value">${c.interviews}<small>个机会</small></div></div><div class="stat-card"><div class="stat-top">已完成行动 <span class="stat-icon">✓</span></div><div class="stat-value">${c.done}<small>件小事</small></div></div></div>
    <div class="section-head"><div><h2>今天做什么</h2><p>先完成一件，就会比昨天更接近目标</p></div><button class="text-link" data-action="go-direction">管理行动清单 ↗</button></div><div class="two-col"><div class="panel"><div class="panel-head"><h3>我的行动清单</h3><span class="pill">${c.done}/${state.tasks.length} 已完成</span></div>${state.tasks.length?`<div class="progress-rail"><i style="width:${progress}%"></i></div><div class="task-list">${pending.length?pending.map(taskHTML).join(''):'<div class="callout">做得好！目前的行动已全部完成，可以继续为自己添加一个新目标。</div>'}</div>`:`<div class="callout"><strong>先从方向开始。</strong>填写你的目标岗位和现有经验，我们会为你生成一组起步行动。</div>`}<form class="task-form" id="task-form"><input class="input" name="title" maxlength="100" required placeholder="添加一件自己的小事…" aria-label="新行动"><button class="btn btn-ghost" type="submit">添加</button></form></div><div class="panel"><div class="panel-head"><h3>最近的投递</h3><button class="text-link" data-action="go-tracker">查看全部 ↗</button></div>${recent.length?`<div class="timeline">${recent.map(j=>`<div class="timeline-item"><i class="timeline-dot"></i><div><strong>${esc(trunc(j.company,35))} · ${esc(trunc(j.role,35))}</strong><span>${esc(j.status)} · ${esc(j.date||'未填日期')}</span></div></div>`).join('')}</div>`:`<div class="analysis-empty" style="min-height:170px"><div><b>◎</b><p>还没有投递记录。发现感兴趣的岗位后，把进度记在这里。</p><button class="btn btn-ghost btn-sm" data-action="add-job">记录一份机会</button></div></div>`}</div></div>
    <div class="section-head"><div><h2>沿着你的节奏，继续走</h2><p>这里的工具都可以独立使用</p></div></div><div class="cards-3"><div class="feature-card"><span class="feature-icon"><svg class="nav-icon" aria-hidden="true"><use href="./icons.svg#compass"></use></svg></span><h3>找到更清晰的方向</h3><p>对照目标岗位的要求和自己已有的证据，看到下一步该补什么。</p><a href="#direction">去看看 ↗</a></div><div class="feature-card"><span class="feature-icon"><svg class="nav-icon" aria-hidden="true"><use href="./icons.svg#file"></use></svg></span><h3>写一份真实的简历</h3><p>用经历和成果讲清楚自己，直接打印或另存为 PDF。</p><a href="#resume">开始整理 ↗</a></div><div class="feature-card"><span class="feature-icon"><svg class="nav-icon" aria-hidden="true"><use href="./icons.svg#shield"></use></svg></span><h3>识别招聘风险</h3><p>检查广告里的常见危险信号，再去官方渠道核对。</p><a href="#safety">检查一下 ↗</a></div></div>`}
  function taskHTML(t){return `<div class="task ${t.done?'done':''}"><input type="checkbox" aria-label="完成这项行动" data-task="${esc(t.id)}" ${t.done?'checked':''}><span class="task-body"><span class="task-title">${esc(trunc(t.title,130))}</span><span class="task-meta">${esc(t.source==='plan'?'根据你的目标生成':'自己添加')}</span></span><button class="icon-button" type="button" data-action="delete-task" data-id="${esc(t.id)}" aria-label="删除这项行动">×</button></div>`}
  function planTasks(){const role=trunc(state.profile.target||'目标岗位',36),status=state.profile.status;return [
    `在公共招聘平台找 3 个「${role}」岗位，保存岗位要求`,
    `梳理 2 段能证明自己适合「${role}」的经历或作品`,
    `针对一个真实岗位修改简历，并核对招聘方信息`,
    status==='转行探索'?'列出已有技能可迁移到新岗位的 3 个例子':status==='应届毕业'?'准备一段 60 秒的自我介绍':'复盘一份投递，写下下一次可以改进的地方'
  ].map(title=>({id:uid(),title,done:false,source:'plan'}))}
  const skills=['Excel','SQL','Python','Java','JavaScript','React','Vue','运营','数据分析','项目管理','产品设计','用户研究','沟通','销售','客户服务','财务','会计','剪辑','设计','UI','测试','文案','英语','供应链','新媒体','电商','客服','招聘','Photoshop','CAD','AutoCAD','护理','教育','教学','机械','电气','行政','短视频','直播','市场','采购','仓储','小程序','人工智能','机器学习'];
  function analyse(){const jd=state.analysisInput.jd||'',evidence=`${state.analysisInput.evidence||''} ${Object.values(state.resume).join(' ')} ${state.profile.strengths||''}`;const mentioned=skills.filter(s=>jd.toLowerCase().includes(s.toLowerCase())).slice(0,16);return {mentioned,covered:mentioned.filter(s=>evidence.toLowerCase().includes(s.toLowerCase())),missing:mentioned.filter(s=>!evidence.toLowerCase().includes(s.toLowerCase()))}}
  function direction(){const p=state.profile,a=analyse();return `${header('01 / DISCOVER','先定方向，再迈步','写下你现在的位置和想去的方向。内容只保存在当前浏览器。')}<div class="split"><div class="panel"><div class="panel-head"><h2>我的求职坐标</h2><span class="pill">可随时修改</span></div><form id="profile-form"><div class="form-grid"><label class="field">目前的状态<select name="status"><option value="">请选择</option>${['应届毕业','正在求职','在职探索','转行探索','重返职场'].map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="field">想去的城市<input name="city" maxlength="40" value="${esc(p.city)}" placeholder="例如：成都 / 不限"></label><label class="field wide">目标岗位 <small>可以先写一个方向</small><input name="target" required maxlength="60" value="${esc(p.target)}" placeholder="例如：产品运营、前端开发、财务助理"></label><label class="field wide">我已经具备的经验或技能<textarea name="strengths" maxlength="1200" placeholder="写下做过的项目、工作、实习或擅长的工具">${esc(p.strengths)}</textarea></label><label class="field wide">现在最想解决的问题<textarea name="goal" maxlength="500" placeholder="例如：不知道怎么选岗位 / 简历总是没回应">${esc(p.goal)}</textarea></label></div><div class="form-actions"><button class="btn btn-dark" type="submit">保存方向并生成行动 ↗</button></div></form></div><div class="panel"><div class="panel-head"><h2>岗位要求对照</h2><span class="pill orange">文本辅助工具</span></div><p class="subtle">粘贴一个真实岗位的要求，再写下你的经历。我们只找出常见关键词是否出现，不能判断录用概率或真实胜任力。</p><form id="analysis-form"><label class="field">岗位要求<textarea name="jd" maxlength="8000" style="min-height:120px" placeholder="粘贴岗位描述中的职责和要求">${esc(state.analysisInput.jd)}</textarea></label><label class="field">我的相关经历<textarea name="evidence" maxlength="5000" style="min-height:90px" placeholder="例如：做过数据分析项目，熟悉 Excel 和 SQL">${esc(state.analysisInput.evidence)}</textarea></label><div class="form-actions"><button class="btn btn-ghost" type="submit">对照一下 ↗</button></div></form></div></div>
    <div class="section-head"><div><h2>对照结果</h2><p>只依据你填写的文字作提示，遗漏词不等于缺少能力</p></div></div><div class="panel" id="analysis-result">${state.analysisInput.jd?analysisHTML(a):`<div class="analysis-empty"><div><b>◇</b><p>贴入一个具体岗位要求，结果会出现在这里。</p></div></div>`}</div>
    <div class="section-head"><div><h2>我的行动清单</h2><p>每一项都可以完成或删除，也可以添加自己的安排</p></div></div><div class="panel"><div class="task-list">${state.tasks.length?state.tasks.map(taskHTML).join(''):'<div class="callout">保存一次求职方向，就会生成一份起步清单。</div>'}</div><form class="task-form" id="task-form"><input class="input" name="title" maxlength="100" required placeholder="添加一个具体行动…" aria-label="新行动"><button class="btn btn-ghost" type="submit">添加</button></form></div>`}
  function analysisHTML(a){return a.mentioned.length?`<div class="mini-label">岗位描述中识别到的常见技能词（${a.mentioned.length} 个）</div><div class="keyword-grid">${a.mentioned.map(s=>`<span class="pill">${esc(s)}</span>`).join('')}</div><div class="mini-label">你的文字中也出现了</div><div class="keyword-grid">${a.covered.length?a.covered.map(s=>`<span class="pill">✓ ${esc(s)}</span>`).join(''):'<span class="subtle">暂未识别到重合词。换种写法或补充具体例子试试。</span>'}</div><div class="mini-label">值得核实的词</div><div class="keyword-grid">${a.missing.length?a.missing.map(s=>`<span class="pill orange">? ${esc(s)}</span>`).join(''):'<span class="subtle">本词表内没有待核实项，仍需逐条阅读岗位要求。</span>'}</div><div class="recommend">下一步：挑出一项岗位要求，写一条「我做了什么、怎么做、结果如何」的真实经历；没有做过的内容不要写进简历。</div>`:`<div class="callout"><strong>暂未识别出预设词表中的技能词。</strong>请人工阅读岗位要求，圈出反复出现的职责、工具与经验，再用真实经历逐项对照。本工具的词表有限。</div>`}
  function resumePaper(){const r=state.resume;return `<article class="resume-paper"><h2>${esc(r.name)||'你的名字'}</h2><div class="role">${esc(r.title)||'目标岗位'}</div><div class="contact">${[r.phone,r.email,r.city].filter(Boolean).map(x=>esc(x)).join(' · ')||'联系方式 · 所在城市'}</div>${[['个人简介','summary'],['工作 / 实习经历','experience'],['项目 / 作品经历','projects'],['教育经历','education'],['技能与工具','skills']].map(([title,key])=>`<h3>${title}</h3><p class="${r[key]?'':'paper-placeholder'}">${r[key]?nl(r[key]):'在左侧填写后，这里会实时显示。'}</p>`).join('')}</article>`}
  function resume(){const r=state.resume;const field=(label,key,placeholder,rows=3)=>`<label class="field">${label}<textarea name="${key}" rows="${rows}" maxlength="4000" placeholder="${placeholder}">${esc(r[key])}</textarea></label>`;return `${header('02 / TELL YOUR STORY','把经历，写成有说服力的简历','只写真实做过的事。填写时右侧同步预览，完成后可打印或另存为 PDF。')}<div class="resume-layout"><div class="panel resume-form"><div class="panel-head"><h2>填写内容</h2><span class="pill">自动保存</span></div><form id="resume-form"><div class="form-grid"><label class="field">姓名<input name="name" maxlength="60" value="${esc(r.name)}" placeholder="姓名"></label><label class="field">目标岗位<input name="title" maxlength="80" value="${esc(r.title)}" placeholder="例如：运营专员"></label><label class="field">电话<input name="phone" maxlength="50" value="${esc(r.phone)}" placeholder="手机号"></label><label class="field">邮箱<input name="email" maxlength="120" value="${esc(r.email)}" placeholder="邮箱"></label><label class="field wide">所在城市<input name="city" maxlength="60" value="${esc(r.city)}" placeholder="城市"></label></div><div class="section-hint" style="margin:20px 0 16px">小提示：每段经历尽量写清「做了什么 → 如何做 → 有什么结果」。能量化就写真实数字，不能量化就说清具体变化。</div>${field('个人简介','summary','用两三句话概括与你的目标岗位相关的经验')}${field('工作 / 实习经历','experience','单位 · 岗位 · 时间\n做了什么、怎么做、结果如何',5)}${field('项目 / 作品经历','projects','项目名称 · 你的角色\n目标、行动和结果；可以写公开作品链接',5)}${field('教育经历','education','学校 · 专业 · 时间；也可写相关课程或培训')}${field('技能与工具','skills','只填写掌握且能举例说明的技能')}<div class="form-actions"><button class="btn btn-dark" type="button" data-action="print">打印 / 保存为 PDF ↗</button><button class="btn btn-ghost" type="button" data-action="copy-resume">复制文本</button></div></form></div><div class="resume-preview-tools"><div class="panel-head"><h2>简历预览</h2><span class="subtle">A4 简洁版式</span></div><div id="resume-preview">${resumePaper()}</div><p class="subtle">打印时请选择“另存为 PDF”。打印预览只显示简历内容。</p></div></div>`}
  function tracker(){const list=filter==='全部'?state.jobs:state.jobs.filter(j=>j.status===filter);return `${header('03 / KEEP MOVING','每一次投递，都有迹可循','把岗位、日期和反馈记下来，少一点混乱，多一点掌控感。')}<div class="track-toolbar"><div class="segmented" aria-label="筛选状态">${['全部',...stages].map(s=>`<button type="button" data-action="filter" data-filter="${s}" class="${filter===s?'active':''}">${s}${s==='全部'?` ${state.jobs.length}`:''}</button>`).join('')}</div><div class="spacer"></div><button class="btn btn-outline btn-sm" data-action="export-csv" ${!state.jobs.length?'disabled':''}>导出 CSV</button><button class="btn btn-dark" data-action="add-job">＋ 记录岗位</button></div><div class="job-list">${list.length?list.map(j=>`<article class="job-card"><div><h3>${esc(trunc(j.company,100))} · ${esc(trunc(j.role,100))}</h3><p>${esc(j.date||'未填日期')} · ${esc(trunc(j.source||'来源未填',80))}${j.url&&safeUrl(j.url)?` · <a target="_blank" rel="noopener noreferrer" class="text-link" href="${esc(safeUrl(j.url))}">岗位链接 ↗</a>`:''}</p>${j.notes?`<p class="notes">${nl(trunc(j.notes,500))}</p>`:''}</div><div class="job-actions"><label class="sr-only" for="status-${esc(j.id)}">投递状态</label><select class="status-select" id="status-${esc(j.id)}" data-job-status="${esc(j.id)}">${stages.map(s=>`<option ${j.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="btn btn-ghost btn-sm" data-action="edit-job" data-id="${esc(j.id)}">编辑</button><button class="icon-button" data-action="delete-job" data-id="${esc(j.id)}" aria-label="删除这条记录">×</button></div></article>`).join(''):empty('▥',filter==='全部'?'从第一份机会开始':'当前筛选没有记录',filter==='全部'?'找到岗位后记下公司、来源与下一次跟进时间。':'切换其他状态，看看你的求职进展。',filter==='全部'?'<button class="btn btn-dark" data-action="add-job">记录第一份岗位</button>':'')}</div><div class="notice">记录的是你自己提供的信息，不会自动向招聘方投递，也不会抓取或验证岗位。离开本浏览器前可在设置中导出备份。</div>`}
  const checks=[['收费 / 贷款','入职前要求培训费、押金、贷款，或承诺“包就业”“保录用”时先停下核实。','high',/(培训贷|招转培|招转贷|付费内推|包就业|保录|保offer|保证录用|交押金|入职费|手续费|培训费|贷款|分期付款|直签)/i],['高收益 / 拉群','以异常高回报、日结任务或刷单引导转账、垫资，风险很高。','high',/(刷单|垫资|先付款|先转账|高薪日结|躺赚|稳赚|充值返佣|拉群|做任务返现)/i],['身份与沟通','要求先交身份证原件、银行卡或验证码，或只用私人社交账号沟通，应核实企业与岗位。','medium',/(身份证原件|银行卡密码|验证码|私人微信|私人qq|扣押证件|缴纳保证金)/i],['夸大承诺','“无经验高薪”“无需面试直接录用”等绝对表述值得进一步核实。','medium',/(无经验高薪|无需面试|直接录用|央企内推|国企内推|内部名额|百分百入职|100%录用)/i]];
  function riskHTML(input){if(!input.trim())return `<div class="analysis-empty safety-result"><div><b>✳</b><p>粘贴招聘文案后，常见风险词会在这里列出。</p></div></div>`;const matches=checks.filter(c=>c[3].test(input));return matches.length?`<div class="pill red">发现 ${matches.length} 类需要核实的信号</div>${matches.map(c=>`<div class="risk-item risk-${c[2]}"><strong>${c[2]==='high'?'● 高度留意':'● 建议核实'} · ${c[0]}</strong><p>${c[1]}</p></div>`).join('')}<p class="subtle">这只是关键词提示，不能证明招聘方违法或岗位一定有问题。请通过企业官网、公开招聘渠道和当地人社部门核实。</p>`:`<div class="callout"><strong>未命中预设风险词。</strong>这不代表岗位安全。仍需查企业主体、面试地点、合同与收费情况，不要凭这一结果作决定。</div>`}
  function safety(){return `${header('04 / STAY SAFE','机会重要，安全更重要','用一份简单的自查清单，识别求职过程中的常见风险。')}<div class="split"><div class="panel"><div class="panel-head"><h2>招聘信息检查</h2><span class="pill orange">离线关键词检查</span></div><p class="subtle">复制一段招聘广告或沟通文字。内容只在本页临时处理，不会保存到本地记录。</p><form id="risk-form"><label class="field">待检查的文字<textarea name="text" maxlength="12000" style="min-height:190px" placeholder="把招聘广告中的岗位描述、收费要求或沟通内容粘贴到这里…">${esc(riskText)}</textarea></label><div class="form-actions"><button class="btn btn-dark" type="submit">检查风险信号 ↗</button></div></form></div><div class="panel"><div class="panel-head"><h2>检查结果</h2></div><div id="risk-result">${riskHTML(riskText)}</div></div></div><div class="section-head"><div><h2>投递前的 4 个核对动作</h2><p>这些动作比“看起来正规”更可靠</p></div></div><div class="panel"><ul class="checks"><li>从企业官网、正规招聘渠道或公共就业服务平台反查岗位与联系人。</li><li>核实实际工作内容、地点、薪酬结构、劳动合同和招聘主体。</li><li>遇到入职前收费、培训贷款、付费内推、保录用承诺，暂停付款与签约。</li><li>不要在未经核实的渠道发送身份证照片、银行卡信息或验证码。</li></ul></div><div class="notice">参考：人社部门等公开发布的招聘欺诈典型案例与风险提示。遇到疑似侵权或诈骗，请保留证据并向当地人社部门或公安机关咨询、反映。</div>`}
  function resources(){const items=[['公共招聘','中国公共招聘网','人社部门的公共招聘入口，可浏览岗位、招聘会等信息。','https://job.mohrss.gov.cn/','全体求职者'],['高校就业','国家大学生就业服务平台','面向高校毕业生的就业服务与招聘信息入口。','https://www.ncss.cn/','高校毕业生'],['职业服务','中国就业网','查询就业政策、求职指导、技能培训等公开信息。','https://chinajob.mohrss.gov.cn/','全体求职者'],['风险提示','招聘欺诈典型案例','人社部、中央网信办、教育部联合发布的公开案例。','https://www.cac.gov.cn/2025-05/23/c_1749711539829884.htm','防范风险'],['风险提示','“招转培”“培训贷”提示','多部门发布的风险提示，帮助识别培训贷款陷阱。','https://www.mohrss.gov.cn/wap/xw/rsxw/202605/t20260515_576264.html','防范风险']];return `${header('05 / REAL-WORLD RESOURCES','去真实世界，找到真实机会','这里提供公开的官方入口。岗位信息会变化，请在原网站核实最新内容。')}<div class="resources-grid">${items.map(([tag,title,desc,url,audience])=>`<article class="resource-card"><div class="resource-tag">${tag.toUpperCase()}</div><h3>${title}</h3><p>${desc}</p><small>适用：${audience}</small><a href="${url}" target="_blank" rel="noopener noreferrer">访问官方网站 ↗</a></article>`).join('')}</div><div class="notice">下一步不是招聘平台，也不代理投递或担保录用。页面中的公共资源是跳转入口，具体服务与内容以原站为准。</div>`}
  function companion(){return window.NextStepCompanion?.view({profile:state.profile,resume:state.resume,analysis:state.analysisInput}) || '<p>伙伴正在载入…</p>'}
  function render(){const name=route();document.body.classList.remove('companion-panel-open');$('#main').classList.toggle('companion-route',name==='companion');$('#main').innerHTML=({overview,direction,companion,resume,tracker,safety,resources})[name]();$('#crumb-title').textContent=names[name];document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===name);a.setAttribute('aria-current',a.dataset.nav===name?'page':'false')});const more=$('#mobile-more');more?.classList.toggle('active',['tracker','safety','resources'].includes(name));if(more)more.open=false;if(name==='companion')window.NextStepCompanion?.mount($('#main'),{profile:state.profile,resume:state.resume,analysis:state.analysisInput});$('#today-label').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}
  function openModal(content){$('#dialog-root').innerHTML=`<div class="modal-backdrop" data-backdrop="true"><div class="modal" role="dialog" aria-modal="true" aria-label="${esc(content.title)}"><div class="modal-head"><h2>${esc(content.title)}</h2><button class="close" data-action="close-modal" aria-label="关闭">×</button></div>${content.body}</div></div>`;$('.modal').querySelector('input,button,select')?.focus();document.body.style.overflow='hidden'}
  function closeModal(){if(!$('#dialog-root').innerHTML)return;$('#dialog-root').innerHTML='';document.body.style.overflow=''}
  function jobModal(id){const j=state.jobs.find(x=>x.id===id)||{company:'',role:'',source:'',url:'',date:today(),notes:'',status:'想投递'};openModal({title:id?'编辑岗位':'记录一份机会',body:`<form id="job-form" data-id="${esc(id||'')}"><label class="field">公司 / 机构 *<input name="company" required maxlength="100" value="${esc(j.company)}" placeholder="企业名称"></label><label class="field">岗位名称 *<input name="role" required maxlength="100" value="${esc(j.role)}" placeholder="岗位名称"></label><div class="form-grid"><label class="field">记录日期<input name="date" type="date" value="${esc(j.date)}"></label><label class="field">状态<select name="status">${stages.map(s=>`<option ${s===j.status?'selected':''}>${s}</option>`).join('')}</select></label></div><label class="field">岗位来源<input name="source" maxlength="100" value="${esc(j.source)}" placeholder="例如：企业官网 / 招聘会"></label><label class="field">岗位链接<input name="url" type="url" maxlength="1000" value="${esc(j.url)}" placeholder="https://…"></label><label class="field">备注 / 下一步<textarea name="notes" maxlength="2000" placeholder="例如：周四跟进邮件；准备作品集">${esc(j.notes)}</textarea></label><div class="form-actions"><button class="btn btn-ghost" type="button" data-action="close-modal">取消</button><button class="btn btn-dark" type="submit">保存记录</button></div></form>`})}
  function settings(){openModal({title:'数据与设置',body:`<p class="subtle">你的求职资料保存在当前浏览器的本地存储中。清除浏览器数据或更换设备可能使记录消失，建议定期导出备份。</p><div class="settings-row"><div><strong>导出完整备份</strong><span>生成包含简历与投递记录的 JSON 文件</span></div><button class="btn btn-ghost btn-sm" data-action="export-json">导出</button></div><div class="settings-row"><div><strong>导入备份</strong><span>导入会替换当前浏览器中的数据</span></div><label class="btn btn-ghost btn-sm file-pick">选择文件<input id="import-file" type="file" accept="application/json,.json"></label></div><div class="settings-row"><div><strong>清空本地数据</strong><span>删除本页面保存的简历、方向、行动和投递</span></div><button class="btn btn-danger btn-sm" data-action="reset">清空</button></div><p class="subtle" style="margin-top:20px">本工具不提供账号同步、自动投递或招聘信息真实性担保。</p>`})}
  function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function resumeText(){const r=state.resume;return [r.name,r.title,[r.phone,r.email,r.city].filter(Boolean).join(' · '),'个人简介',r.summary,'工作 / 实习经历',r.experience,'项目 / 作品经历',r.projects,'教育经历',r.education,'技能与工具',r.skills].filter(Boolean).join('\n\n')}
  function csv(){const fields=['公司','岗位','日期','状态','来源','链接','备注'];const cell=v=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\ufeff'+[fields.map(cell).join(','),...state.jobs.map(j=>[j.company,j.role,j.date,j.status,j.source,j.url,j.notes].map(cell).join(','))].join('\r\n')}
  document.addEventListener('click',e=>{if(e.target.dataset.backdrop){closeModal();return}const el=e.target.closest('[data-action]');if(!el)return;const id=el.dataset.id;switch(el.dataset.action){case'go-direction':go('direction');break;case'go-companion':go('companion');break;case'go-tracker':go('tracker');break;case'add-job':jobModal();break;case'edit-job':jobModal(id);break;case'delete-job':if(confirm('删除这条投递记录？')){state.jobs=state.jobs.filter(j=>j.id!==id);save();render();toast('记录已删除')}break;case'delete-task':state.tasks=state.tasks.filter(t=>t.id!==id);save();render();break;case'filter':filter=el.dataset.filter;render();break;case'close-modal':closeModal();break;case'print':window.print();break;case'copy-resume':if(navigator.clipboard?.writeText){navigator.clipboard.writeText(resumeText()).then(()=>toast('简历文本已复制')).catch(()=>toast('复制失败，请手动选择文字'))}else toast('当前浏览器不支持自动复制，请手动选择简历文字');break;case'export-json':download(`下一步-备份-${today()}.json`,JSON.stringify({app:'下一步',version:1,exportedAt:new Date().toISOString(),data:state,companionMemory:localStorage.getItem('xiayibu-companion-memory-v1')||''},null,2),'application/json');toast('备份已下载，请妥善保管');break;case'export-csv':if(state.jobs.length)download(`下一步-投递记录-${today()}.csv`,csv(),'text/csv;charset=utf-8');break;case'reset':if(confirm('确定清空此浏览器中“下一步”的所有数据吗？此操作无法撤销。')){state=defaults();localStorage.removeItem(KEY);localStorage.removeItem('xiayibu-companion-memory-v1');closeModal();render();toast('本地数据已清空')}break}});
  document.addEventListener('submit',e=>{const form=e.target;if(!['profile-form','analysis-form','task-form','job-form','risk-form','resume-form'].includes(form.id))return;e.preventDefault();const d=Object.fromEntries(new FormData(form));if(form.id==='profile-form'){const oldTarget=state.profile.target;state.profile={status:trunc(d.status,40),city:trunc(d.city,40),target:trunc(d.target,60).trim(),strengths:trunc(d.strengths,1200),goal:trunc(d.goal,500)};if(!state.tasks.length||oldTarget!==state.profile.target){state.tasks=state.tasks.filter(t=>t.source!=='plan').concat(planTasks())}save();render();toast('方向已保存，行动清单已更新')}if(form.id==='analysis-form'){state.analysisInput={jd:trunc(d.jd,8000),evidence:trunc(d.evidence,5000)};save();render();$('#analysis-result')?.scrollIntoView({behavior:'smooth',block:'start'})}if(form.id==='task-form'){const title=trunc(d.title,100).trim();if(title){state.tasks.push({id:uid(),title,done:false,source:'custom'});save();render();toast('已添加一项行动')}}if(form.id==='job-form'){const id=form.dataset.id;const url=trunc(d.url,1000).trim();if(url&&!safeUrl(url)){toast('岗位链接请使用 http 或 https');return}const item={id:id||uid(),company:trunc(d.company,100).trim(),role:trunc(d.role,100).trim(),date:trunc(d.date,10),status:stages.includes(d.status)?d.status:'想投递',source:trunc(d.source,100),url,notes:trunc(d.notes,2000)};if(!item.company||!item.role)return;if(id){state.jobs=state.jobs.map(j=>j.id===id?item:j)}else state.jobs.unshift(item);save();closeModal();render();toast(id?'记录已更新':'机会已记录')}if(form.id==='risk-form'){riskText=trunc(d.text,12000);$('#risk-result').innerHTML=riskHTML(riskText);toast('检查完成，请结合实际情况核实')}});
  document.addEventListener('change',e=>{if(e.target.matches('[data-task]')){const t=state.tasks.find(x=>x.id===e.target.dataset.task);if(t){t.done=e.target.checked;save();render()}}if(e.target.matches('[data-job-status]')){const j=state.jobs.find(x=>x.id===e.target.dataset.jobStatus);if(j&&stages.includes(e.target.value)){j.status=e.target.value;save();render();toast('状态已更新')}}if(e.target.id==='import-file'){const file=e.target.files?.[0];if(!file)return;if(file.size>2_000_000){toast('备份文件超过 2 MB，无法导入');return}file.text().then(s=>{const parsed=JSON.parse(s);if(parsed.app!=='下一步'||parsed.version!==1||!parsed.data||!Array.isArray(parsed.data.jobs)||!Array.isArray(parsed.data.tasks))throw Error('format');if(!confirm('导入将替换当前浏览器内的所有求职数据，继续吗？'))return;localStorage.setItem(KEY,JSON.stringify(parsed.data));if(typeof parsed.companionMemory==='string')localStorage.setItem('xiayibu-companion-memory-v1',parsed.companionMemory.slice(0,2000));state=load();closeModal();render();toast('备份已导入')}).catch(()=>toast('文件格式不符合“下一步”备份格式'))}});
  document.addEventListener('input',e=>{if(e.target.closest('#resume-form')){const data=Object.fromEntries(new FormData($('#resume-form')));for(const key of Object.keys(defaults().resume))state.resume[key]=trunc(data[key],4000);$('#resume-preview').innerHTML=resumePaper();clearTimeout(saveTimer);saveTimer=setTimeout(save,300)}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
  $('#settings-open').addEventListener('click',settings);
  window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});
  render();
})();
